### ISSUE TITLE
Upgrade to 5.4.5

### ISSUE THREAD

**Issue by acarabott** [varp/sublime-psutil#1]
Hey, thanks for supporting this.

Would you be able to upgrade to 5.4.5? It fixes an issue with zombie processes on MacOS:

https://github.com/giampaolo/psutil/commit/f435c2b6d308c12d0df33b10d828d97df303a614

Cheers!

**Comment by varp** [comment]
Hey, sorry for the late answer. At the time I don't have spare time... I'll do an attempt at holidays

**Comment by acarabott** [comment]
Totally understand!

I've also realised that they have dropped support for Python < 3.5 so I think this won't actually be possible until Sublime upgrades its Python runtime 😕

**Comment by varp** [comment]
@acarabott I've recompiled and updated libs and files on Linux(amd64 for now), Windows(x86,amd64) and OSX(amd64) platforms to 5.4.6 based on Python version embedded with ST3 (3.3.6).

I think to the middle of the next week, I'll update `.travis.yml` to compile x86 libs and then will do PR to the Package Control Channel with updated stuff. It would be nice if you can help with this. Just do a PR to my fork of [psutil](https://github.com/varp/psutil)

**Comment by acarabott** [comment]
@varp Great stuff. I'm happy to help with the Package Control stuff, but am not familiar with travis. Let me know if that would help!

**Comment by varp** [comment]
@acarabott all is done. A PR is made to package_control_channel.

**Comment by acarabott** [comment]
Awesome, much appreciated. Apologies that I couldn't be more of a help.
